### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by eren23** [ThingType/DW1000_Python_library#1]
Hi, 
First of all thank you for reading this comment im trying to use your code with my rasp0w, but i can't make it work properly. [https://www.raspberrypi.org/forums/viewtopic.php?f=29&t=202956&p=1261127#p1261127](url) this is the error that i get when i try to run your code.
Any idea about how can i solve it? 
Regards
Eren

**Comment by Naaver** [comment]
Hello,
I have encountered the same error a while ago.  I have checked the original library and found that  two constants are missing in file "DW1000Constants.py":
FFEN_BIT = 0
DIS_STXP_BIT = 18
Just place them under "# System configuration register bits, see 7.2.6 of User Manual" (line 164) .It should now compile without error then BUT the I have encountered another problem; Pi is communicating with DW but the output is wrong. In Device ID field I got "FFFF" instead of "DECA" the unique ID is also made of "F". 
Best Regards,

**Comment by eren23** [comment]
Hi Naaver ty for your answer it has worked as you said, and againas you said im having troubles with that FFFF thing, i think it can be related with our connections, cause in my case it turns like "model:255 version:15 revision:15" so it's probably about wiring i'm gonna try to fix it when i have time i'm kinda busy atm, i'll send schematics if i can solve the problem, maybe you can go on the wires aswell. Thanks again for your help :)

**Comment by Naaver** [comment]
Hello,

I have checked the wiring few times, tried with rpi 0 and rpi 1, yet still got the same  random data on the output. Looks like it reads random things from the memory , I will try to figure where the problem is.

**Comment by eren23** [comment]
Hello,
Yeah i've checked wiring also, it seems there isn't anything going wrong about wiring. So i think it can be about the difference of length of message that we try send/receive. I'm going to watch that communication between dw1000 and rasp with a logic analyser. If there is something odd with message length i think with that way it can find and fix that way. If you have a logic analyser you may want to check this out to, i'll post here if i can make any progress, have a good day.

**Comment by eren23** [comment]
Hi, i've checked communication between rasp and dw1000 and it's pretty broken, however with the same rasp i can communicate with nrf24l0 over spi wo any problems. So it's probably the communication speed that broke our communication, currently i'm trying to descend it to 1mhz.

**Comment by Naaver** [comment]
Hello,

I have tried  changing the self.spi.max_speed_hz. It indeed changed the output but it is still gibberish and going below certain value will change everything to 0. I was also experimenting with cables,tried to shield them from the environment but without much success.

**Comment by TTrml** [comment]
Hi there,

Indeed we were missing the DIS_STXP_BIT and FFEN_BIT mentioned by Naaver, the fix has been committed.
Cheers,

Armel

**Comment by TTrml** [comment]
Also you might want to try to uncomment line 49 in DW1000.py (see latest commit), it has been reported to fix communications issues. Let us know how it works out for you!

**Comment by eren23** [comment]
Actually it didn't work out for me with that last update too, i just forgot to mention about it i'm kinda busy in nowadays, i'm sorry about that. Also i can't view correct communucation when i try to watch communucation with a logic analyser and again i' apologies for responding that late. 

Regards

**Comment by Naaver** [comment]
Hello,

I'm sorry I could reply earlier, I was very busy too, I have found more errors in the file DW1000.py:
Line 700:
            writeValueToBytes(data, C.LDE_REPC_3, 2)
After changing LDE_REPC_3 to LDE_REPC_3AND8 the setup finally started to work.
I have also found some warning in the code, starting line 1216:
The variable "len" is a built-in symbol and should not be assigned. But I don't think this is affecting anything to much. I also have tried to compile the code using python3 but I got error. I will try to investigate it more when I will have some free time.

**Comment by eren23** [comment]
Hi Naaver,

Ty for your response again i've tried the solution that you've mentioned as soon as i had time but the result is still the same for me. Is changing "LDE_REPC_3AND8" really work your Raspi %100? I'm trying to get it work with my Raspi Zero W, i'm also going to try the same with raspi 3, btw what is the communication speed that you've set for your setup. Please let me know if you have any progress about this matter, i'm really grateful for the information that you've shared so far with me. 

Thank you

**Comment by eren23** [comment]
This is the latest output from debug screen of my application. https://pastebin.ubuntu.com/p/y2WBMH69y7/

**Comment by Naaver** [comment]
Hello,

Sorry for the late answer, I was really busy here. After doing the changes I have mentioned before it worked, but there are still multiple problems with measuring the distance it self, the signal usually dies out around 6 meter, I have left the default communication speed. The "reset inactive" communicate in fact is quite a good sign, I was getting those in the begging.  The "FFFF" output is where the "DECA" should be?

**Comment by eren23** [comment]
Hi, yes "FFFF" output is comes out where the "DECA" should be, i've never had a chance to take a look at this project since i left the comment above so nothing much changed on my side :D

**Comment by TTrml** [comment]
Hi guys,
If you are still facing communications issues when talking to the module (e.g. FFFF), you could try monitoring the electrical signal with a logic analyzer or oscilloscope. Send simple commands to the module (using the library or soem other code) and check if the data that goes back and forth is as expected.

**Comment by eren23** [comment]
Hi,

I've already tried with the logic analyzer. Communication has some
problems, but i don't really know how to fix them.

2018-03-06 10:27 GMT+03:00 TTrml <notifications@github.com>:

**Comment by Naaver** [comment]
Hello,

I remember I also have some problems with the communication at first. Can you check if the pins number are correctly assigned? I will upload the corrected files in to my git soon (as a fork), you can try if it works with your device.

**Comment by eren23** [comment]
Hi,

I didn't had a chance to take a look at that project again, but i'll try your fork as soon as you created yours. Please let me know when you do. I can give my mail if you want.
